### ISSUE TITLE
Support STS token

### ISSUE THREAD

**Issue by yin1999** [tu6ge/oss-rs#1]
We can use STS token to access aliyun OSS. The additional work is to add `x-oss-security-token` header. I think it'll be nice to support this in the SDK. But it'seems that it might be a bit difficult to add this.

My recent job may not be good enough, but still leave here: https://github.com/yin1999/aliyun-oss-sdk-rust/tree/support-sts-token

**Comment by tu6ge** [comment]
This have a easy method append `x-oss-security-token`, you append it in headers , and call [this method](https://github.com/yin1999/aliyun-oss-sdk-rust/blob/support-sts-token/src/client.rs#L217). about `Auth` struct, I is updating it , after update, you can add trait to `Auth` struct
