### ISSUE TITLE
获取客户端实例那一行直接报错

### ISSUE THREAD

**Issue by inkwise** [tu6ge/oss-rs#11]
// 获取客户端实例
let client = aliyun_oss_client::client(key_id,key_secret, endpoint, bucket);

thread 'main' panicked at 'called `Res
ult::unwrap()` on an `Err` value: Inva
lidEndPoint', /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/aliyun-o
ss-client-0.10.1/src/types.rs:197:25
stack backtrace:

**Comment by tu6ge** [comment]
传入的 endpoint 值是哪一个

**Comment by tu6ge** [comment]
嗨，@inkwise 请问你的问题解决了吗
