### ISSUE TITLE
CommonPrefixes 转 ObjectPath 的问题

### ISSUE THREAD

**Issue by fireyy** [tu6ge/oss-rs#12]
https://github.com/tu6ge/oss-rs/blob/977db3f7ea0638154bf0f556722cdf44bc33ab5a/src/config.rs#L684

如果是`CommonPrefixes`，末尾带`/`，这里的会报错

```
  <CommonPrefixes>
    <Prefix>apk/2.0.1/</Prefix>
  </CommonPrefixes>
```

**Comment by tu6ge** [comment]
hi, @fireyy , `ObjectPath` 这个类型的作用是对标安全的 OSS 上的文件路径，而 `CommonPrefixes` 对应的是路径名，俗称文件夹，所以说，这两者直接转换的话，会不安全

**Comment by tu6ge** [comment]
这里确实没有考虑到，感谢你的反馈

**Comment by fireyy** [comment]
感谢及时回复，刚刚发现还有一个点，当设置 `Delimiter: QueryValue("/")` 的时候，Contents 可能也会出现
```
  <Contents>
    <Key>apk/</Key>
    <LastModified>2019-08-19T05:58:10.000Z</LastModified>
    <ETag>"xxxx"</ETag>
    <Type>Normal</Type>
    <Size>0</Size>
    <StorageClass>Standard</StorageClass>
  </Contents>
```

`Key` 的末尾也会带 `/`

**Comment by tu6ge** [comment]
> https://github.com/tu6ge/oss-rs/blob/977db3f7ea0638154bf0f556722cdf44bc33ab5a/src/config.rs#L684
> 
> 如果是`CommonPrefixes`，末尾带`/`，这里的会报错
> 
> ```
>   <CommonPrefixes>
>     <Prefix>apk/2.0.1/</Prefix>
>   </CommonPrefixes>
> ```

这个问题已经得到解决，添加了一个新的类型 `ObjectDir`

**Comment by tu6ge** [comment]
> 感谢及时回复，刚刚发现还有一个点，当设置 `Delimiter: QueryValue("/")` 的时候，Contents 可能也会出现
> 
> ```
>   <Contents>
>     <Key>apk/</Key>
>     <LastModified>2019-08-19T05:58:10.000Z</LastModified>
>     <ETag>"xxxx"</ETag>
>     <Type>Normal</Type>
>     <Size>0</Size>
>     <StorageClass>Standard</StorageClass>
>   </Contents>
> ```
> 
> `Key` 的末尾也会带 `/`

关于这个问题，可以使用 [base_object_list](https://docs.rs/aliyun-oss-client/latest/aliyun_oss_client/client/type.ClientArc.html#method.base_object_list) 的方式，将数据导出到自定义的类型中来实现，因为目前内置的 Object 对象是无法关联路径的，

其实这个问题还有一个更好的实现方式，那就是给 `ObjectList` 中的字段 `object_list` 改为泛型，但是这里面涉及到很多适配的工作，目前还无法实现

**Comment by fireyy** [comment]
感谢，使用 [base_object_list](https://docs.rs/aliyun-oss-client/latest/aliyun_oss_client/client/type.ClientArc.html#method.base_object_list) 搞定了。
