### ISSUE TITLE
初学者的一点疑惑

### ISSUE THREAD

**Issue by sunny086** [tu6ge/oss-rs#13]
作者您好，我是一名初学者，看了一些语法希望直接在项目中继续加深认知，请问当前这个项目可以添加一些详细的启动运行和调试的步骤简介吗？盼您回复~

**Comment by sunny086** [comment]
我看到您在md中cargo test --lib --all-features tests和cargo t -q --all-features这两个命令，但是还是一头雾水...

**Comment by tu6ge** [comment]
你好，在 `examples` 目录里有一些例子，
复制根目录下的 `.env-example` 文件为 `.env` 并在里面填充 aliyun 的配置信息，可以连接阿里云的 OSS 进行测试

**Comment by tu6ge** [comment]
> 我看到您在md中cargo test --lib --all-features tests和cargo t -q --all-features这两个命令，但是还是一头雾水...

这是用于运行单元测试的命令，用来检测函数是否可以按照期望的方式运行，或产生期望的结果
