### ISSUE TITLE
Endpoint中美东美西地址错误

### ISSUE THREAD

**Issue by blueskoo** [tu6ge/oss-rs#15]
type.rs的Endpoint中，美东美西的字符串应该为："us-east-1"，不是：“us-east1"，导致域名解析错误

**Comment by tu6ge** [comment]
可以详细说说是哪个方法导致解析错误的吗？

**Comment by blueskoo** [comment]
> 可以详细说说是哪个方法导致解析错误的吗？

美东的Endpoint为：https://oss-us-east-1.aliyuncs.com，.env的配置项ALIYUN_ENDPOINT如果配置为https://oss-us-east-1.aliyuncs.com，错误信息为：EndPoint(InvalidEndPoint)；ALIYUN_ENDPOINT=us-east-1，可以正常工作。

看了一下，原因应该是：Endpoint::new()这个方法中：

<img width="593" alt="WeChatac9f4615c312e99f60d079118e141734" src="https://user-images.githubusercontent.com/2750239/227414753-ce83f59e-897c-428e-a0fa-12984e5cee82.png">

其中US_EAST1的常量应该是“us-east-1"。
<img width="323" alt="WeChatfda0d6c9a95409efe43be98fbac89300" src="https://user-images.githubusercontent.com/2750239/227415075-de148d97-0d62-47a5-af76-5dff8eaacfef.png">

**Comment by tu6ge** [comment]
感谢你能够提供细节，刚才我把他当成自定义格式的可用区了，已经在最新版（v0.11.2）中修复
