### ISSUE TITLE
如何获取object_list里的返回值？

### ISSUE THREAD

**Issue by fireyy** [tu6ge/oss-rs#2]
参考demo里的查询当前 bucket 中的 object 列表，但是返回值 object_list 里的 Object 都是私有属性，无法获取 `size` 和 `last_modified` 等值

**Comment by tu6ge** [comment]
嗯，确实是一个问题，你现在用的是哪个版本，我加个补丁吧

**Comment by fireyy** [comment]
我目前用的是 0.9 版本

**Comment by tu6ge** [comment]
Fixed it in 0.9.1
