### ISSUE TITLE
在URL中包含签名怎么实现

### ISSUE THREAD

**Issue by keilestone** [tu6ge/oss-rs#20]
https://help.aliyun.com/document_detail/31952.html?spm=a2c4g.31951.0.0.4a1a50c56q34Fo
这个里面的签名认证用这个crate可以实现吗

**Comment by tu6ge** [comment]
目前还不支持这种方式

**Comment by tu6ge** [comment]
嗨 @keilestone PR 已经实现，如果着急使用的话，可以参考实现，合并 PR 还需要再等等，还涉及到了一些其他地方的优化

**Comment by keilestone** [comment]
@tu6ge 现在用的其他语言sdK做的微服务，等pr合并吧，辛苦了
