### ISSUE TITLE
使用get_object下载图片，图片的体积会增加1倍左右，且文件打不开，该如何破

### ISSUE THREAD

**Issue by uiboom** [tu6ge/oss-rs#27]
使用get_object下载图片，图片的体积会增加1倍左右，且文件打不开，但是下载json是正常的，代码：
 let content= client.get_object("demo.png", ..).await;
    if content.is_ok() {
        let data = &content.unwrap();
        println!("data长度: {}", data.len());
        let mut file = File::create("demo.png").unwrap();
        file.write_all(data).unwrap();
    }
该如何修改？

**Comment by tu6ge** [comment]
嗨，你的代码不需要修改，是 lib 内部的错误，现在已经修复了

**Comment by uiboom** [comment]
好的，谢谢------------------------------------------------------------------
***@***.***>
日　期：2023年10月26日 14:10:11
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [tu6ge/oss-rs] 使用get_object下载图片，图片的体积会增加1倍左右，且文件打不开，该如何破 (Issue #27)

嗨，你的代码不需要修改，是 lib 内部的错误，现在已经修复了
