### ISSUE TITLE
关于 Object 的 key

### ISSUE THREAD

**Issue by fireyy** [tu6ge/oss-rs#3]
https://github.com/tu6ge/oss-rs/blob/branch0.9/src/object.rs#L180

这里的`key`在未来版本弃用的话，object 的 name 就无法获取到了吧？
比如某些场景需要显示 object 列表，name 应该是有必要的。

**Comment by tu6ge** [comment]
可以通过 base 字段里面的 path 字段获取

**Comment by fireyy** [comment]
base 里的字段好像也是私有，没有提供获取的方法,
是不是得返回类型 `GetObjectInfo`

**Comment by tu6ge** [comment]
可以通过这个方法获取，https://github.com/tu6ge/oss-rs/blob/branch0.9/src/object.rs#L204-L206 或者 [`pieces`](https://github.com/tu6ge/oss-rs/blob/branch0.9/src/object.rs#L264)

**Comment by fireyy** [comment]
感谢，看到了
