### ISSUE TITLE
使用put_file上传一个.log文件时会提示file type is known错误

### ISSUE THREAD

**Issue by asins** [tu6ge/oss-rs#5]
使用put_file上传一个.log文件时会提示file type is known错误，

是否能为put_file提供mime_type的设置入口？不然put_file的可用性就比较低了。

看到内部使用了infer模块，但没有定义像`.md`, `.log`之类的文本文件的类型，这时就只能使用`put_content`方法自己定义`content_type`了。

**Comment by tu6ge** [comment]
是的，infer 库是根据文件内容来判断文件格式的，这个库包含了大多数常用的文件格式判断，由于 `.log`, `.md` 的文件内容千变万化，无法根据 Infer 库来匹配，为了保持库的通用性，减少主观因素，这个只能是谁需要，谁来处理了

**Comment by tu6ge** [comment]
当获取不到文件的 content-type 时，默认使用 application/octet-stream 也许是一个不错的选择，[`Self::DEFAULT_CONTENT_TYPE`](https://github.com/tu6ge/oss-rs/blob/master/src/file.rs#L233)
