### ISSUE TITLE
get_object_list callback `prefix` field should be Vec<String>

### ISSUE THREAD

**Issue by weekitmo** [tu6ge/oss-rs#9]
this is the result when i use nodejs to test.
![image](https://user-images.githubusercontent.com/21186859/212220022-5b8824e8-9ce9-48c3-ac68-3d6acf1a2591.png)
![image](https://user-images.githubusercontent.com/21186859/212220048-e436b854-0978-4d1f-bc31-8208eba69820.png)

When using prefix and delimiter to query together, `prefixes` means the sub folder that contains prefix。in my case, i print `&response.prefix()` only the last one string.

reference：

https://help.aliyun.com/document_detail/84841.html#p-awp-qxy-gu1

**Comment by weekitmo** [comment]
```
    fn set_prefix(&mut self, prefix: &str) -> Result<(), Self::Error> {
        if self.prefix == ""  {
            self.prefix.push_str(&prefix.to_owned())
        } else {
            self.prefix.push_str(format!(",{}", &prefix.to_owned()).as_str());
        }
        
        Ok(())
    }
```
and use it 
```
    let prefixes = response.prefix();
    let vec_prefixes: Vec<&str> = prefixes.split(",").collect();
    for pre in vec_prefixes {
        // TODO
    }
```
This is my adjustment. Maybe you have your own ideas

**Comment by tu6ge** [comment]
I look at [aliyun docs](https://help.aliyun.com/document_detail/187544.html), and find `CommonPrefixes` and `Prefix` is two different field of response.

so, `ObjectList` should add a new filed.  used by save `CommonPrefixes` info

**Comment by weekitmo** [comment]
pretty good
